name: DISYS autograde
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16'
      - name: Check version and install lint
        run: make install
      - name: Run vet and lint
        run: |
          ls -al
          make lint
      - name: Runs unit tests
        run: make test
